updated clean_data.py
bettyyw0120/template pull request #2
Opened 2023-11-07 10:35 UTC by bettyyw0120

Following [Practice Task](https://github.com/gslab-econ/lab-manual/wiki/Practice-Task), I edited the plot_data function in [~data/code/clean_data.py](https://github.com/bettyyw0120/template/blob/1-displaying-percentage-in-histogram-instead-of-counts/data/code/clean_data.py) so that the output histogram in [~data/output/chips_sold.pdf](https://github.com/bettyyw0120/template/blob/1-displaying-percentage-in-histogram-instead-of-counts/data/output/chips_sold.pdf) displays percentages instead of counts. 

Reviewers: @snairdesai @jc-cisneros @ShiqiYang2022

2023-11-07 18:23 UTC, jc-cisneros requested changes
Thanks for the work @bettyyw0120! This looks great. Can you incorporate the updated figure in the paper in the `paper_slides` module? I left a minor comment in the code.

2023-11-07 18:23 UTC, jc-cisneros commented on data/code/clean_data.py
> +def to_percent(y, position):
Minor: Is the second argument used?

2023-11-14 12:22 UTC, bettyyw0120 commented on data/code/clean_data.py
> +def to_percent(y, position):
updated!

2023-11-14 20:42 UTC, jc-cisneros approved these changes
Thanks @bettyyw0120! This looks good to go. The next steps are the following:
- Squash merge to master (this reduces the number of commits shown in master).
- Write a [summary post](https://github.com/gslab-econ/lab-manual/wiki/Workflow.Details#summary) on the issue.

2023-11-21 01:41 UTC, snairdesai commented
Hi @bettyyw0120, just checking in on progress here? Do you need any support with merging and addressing the final PR comments/resolving merge conflicts in #4?

2023-11-21 09:48 UTC, merged